### ISSUE TITLE
generating a pole figure after installation

### ISSUE THREAD

**Issue by mwpriddy** [youngung/texture#1]
I have successfully installed TEXTURE on my work desktop (windows 7; running Python 2.7.6 installed via Enthought) and I attempted to run a simpler version of the UPF_test.ipynb for hexagonal symmetry.

The code I used:

```
from src import cmb
from src import upf
import time
reload(upf)

import numpy as np
import matplotlib.pyplot as plt

mypf = upf.polefigure(ngrain=1000, csym='hexag', cdim=[1,1,1.6235])
t0=time.time()
mypf.pf_new(poles=[[0,0,0,2],[1,0,-1,1]], n_rim=2,lev_opt=0,lev_norm_log=True, nlev=6,cmap='jet',dth=10,dph=10,mn=0.6)
print 'pf_new time:', time.time()-t0
plt.show()
```

A figure is generated, but it is only two circles (the pole figures) without any information inside of them.  

![image](https://cloud.githubusercontent.com/assets/7049686/15753387/bc37af18-28c0-11e6-891c-7f62288aed48.png)

I assume I am doing something wrong in my above code, but I am not sure what it is.  Any thoughts?

**Comment by youngung** [comment]
Matthew:

I was not able to reproduce your problem.

See below what I did:

![screen shot 2016-06-02 at 12 59 12](https://cloud.githubusercontent.com/assets/745653/15753596/de78ec3a-28c1-11e6-9fd1-5d9129d2eebf.png)

Would you be able to type

plt.draw()

to see if there's any change?

**Comment by mwpriddy** [comment]
Yeah, that did it!  I placed `plt.draw()` immediately before `plt.show()` and that populated the image.  I guess the plot wasn't automatically updated within `pf_new`?

![image](https://cloud.githubusercontent.com/assets/7049686/15753856/6d12026e-28c3-11e6-89aa-d30045adb9e9.png)

Thanks for the help!

**Comment by youngung** [comment]
I'm glad it worked but I don't know what caused the problem exactly - it just worked fine on my machine without forcing matplotlib to draw the figure. Might be related with the environment / machine you are using.

**Comment by youngung** [comment]
Something came to my mind is that if you are using the generic Python interpreter, you might have to push matplotlib to draw, which is not necessary in IPython. I wonder if that caused the different result between you and me...

**Comment by mwpriddy** [comment]
hmm, I am not sure.  It could most definitely be a possibility...

On Jun 9, 2016, at 2:41 PM, Youngung Jeong wrote:

Something came to my mind is that if you are using the generic Python interpreter, you might have to push matplotlib to draw, which is not necessary in IPython. I wonder if that caused the different result between you and me...
