### ISSUE TITLE
Generating pole figure for random orientations in hcp

### ISSUE THREAD

**Issue by vamsi1712** [youngung/texture#2]
I am trying to generate pole figure for random orientations in a Bismuth Telluride alloy ( HCP structure). I have my random orientation in an excel sheet. So my question was will I be able to use them in your python code (like you called files in your AZ31 alloy texture example).

Also I have some ebsd files which are in .oim format. Can I use this extension in your python code to generate pole figures? If so how can I do that.

**Comment by youngung** [comment]
1. You should export the the random orientation in the excel sheet to a file that is readable by "upf.polefigure" class.
The "upf.polefigure" allows two types of input data.

a). texture files compatible with VPSC. Particularly, it can read a file with 4 dummy head lines that is followed by discrete orientations written in the Bunge convention.
An example is as below:
> dummy
>   dummy
>  dummy
>  dummy
>   356.000    160.810    264.000      2.990
>     1.000     14.840    285.000      1.710
>   194.000     77.810    331.000      0.410

Basically, what it does in this case is 
`self.gr = np.loadtxt(fname=<filename>, skiprows=4)`
which reads the NumPy array from *filename* with skipping the first 4 lines.

b). If you can export the data in the excel into an NumPy array, you can pass that to upf.polefigure.

2. I am not familiar with the EBSD data format you mentioned. There are two options yet as mentioned in a) and b). If you want to read the file, you'll have to parse the data into a form that is compatible with either a) or b).

**Comment by youngung** [comment]
I'm closing this issue but if you have more questions feel free to post them.
